# Generated by Django 6.0 on 2025-12-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0002_rename_payment_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='is_verified',
            new_name='is_approved',
        ),
    ]
