# Generated by Django 6.0 on 2025-12-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0003_rename_is_verified_sellerprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='discount_percent',
            field=models.BooleanField(default=True),
        ),
    ]
