# Generated by Django 6.0 on 2025-12-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0005_alter_fooditem_discount_percent_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
