# Generated by Django 6.0 on 2025-12-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_phtot',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
