# Generated by Django 6.0 on 2025-12-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0007_customerprofile_profile_phtot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='profile_phtot',
            new_name='profile_photo',
        ),
    ]
