# Generated by Django 6.0 on 2025-12-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0008_rename_profile_phtot_customerprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_items', to='quickapp.foodcategory'),
        ),
    ]
