# Generated by Django 6.0 on 2025-12-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0011_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='food_items', to='quickapp.foodcategory'),
            preserve_default=False,
        ),
    ]
